# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: aws/aws-cli
          prefix: '2.'
        id: awscli_version

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set version info
        run: |
          echo "BUILD_ARCH=$(uname -m)" >> $GITHUB_ENV
          echo "BUILD_VER=$(cat AWSCLI_VERSION)" >> $GITHUB_ENV
          echo "BUILD_BOTOCORE=$(cat BOTOCORE_COMMIT_ID)" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "${{ steps.awscli_version.outputs.tag }}"
          echo "arch: $BUILD_ARCH"
          echo "ver: $BUILD_VER"
          echo "botocore: $BUILD_BOTOCORE"
          export
